### ISSUE TITLE
适用于该项目的Jetson Orin NX 16GB 平台 Jetpack版本

### ISSUE THREAD

**Issue by yucong-zhang** [BestAnHongjun/LMDeploy-Jetson#1]
1.在s5阶段安装torch2.1.0，也就是意味着安装Jetpack5.1.2？这是必须的嘛？
2.在给Orin NX 刷5.1.2的jetpack时，遇到了无法开机的情况，但5.1.1没有这个问题，请问您遇到过该问题吗？
3.在s1的修改config.ini文件中，cache_block_seq_len并不需要修改，此处为笔误吗？

**Comment by cavedweller509** [comment]
1.不是的。文档中提供的torch2.1.0支持JetPack 5.1 (L4T R35.2.1) / JetPack 5.1.1 (L4T R35.3.1) / JetPack 5.1.2 (L4T R35.4.1)。您也可以由官网下载合适的pytorch：https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048 。注意torch版本，对于目前v0.2.4(67f8148)版本，需满足torch<=2.1.2,>=2.0.0。
2.抱歉，没有遇到过。您可以按照官方说明尝试重装。
3.是的，感谢您提的issue，会在下一版本对该情况进行修正。

**Comment by yucong-zhang** [comment]
![屏幕截图 2024-02-26 200057](https://github.com/BestAnHongjun/LMDeploy-Jetson/assets/103311431/9b78461e-2b26-4ada-8bf4-9a958eba4d50)
已成功复现，十分有趣，环境是Jetpack5.1.2
