### ISSUE TITLE
服务器量化问题

### ISSUE THREAD

**Issue by chenyang126** [BestAnHongjun/LMDeploy-Jetson#5]
在第一步服务器量化的时候执行W4A16量化时：
![2024-04-15 12-03-37 的屏幕截图](https://github.com/BestAnHongjun/LMDeploy-Jetson/assets/125660450/558dda49-d678-4100-88f6-ca3088526cde)
遇到如下问题：
![2024-04-15 15-26-30 的屏幕截图](https://github.com/BestAnHongjun/LMDeploy-Jetson/assets/125660450/2522c435-5cb2-4bfe-8a69-f926afc8f855)
ConnectionError: Couldn't reach 'ptb_text_only' on the Hub (SSLError)
请问该如何解决啊？

**Comment by cavedweller509** [comment]
您好，由于量化过程中，lmdeploy需要从HuggingFace下载标定数据集，国内使用可能存在无法访问的情况。可以尝试：

1.使用HF镜像，方法：

```sh
export HF_ENDPOINT='https://hf-mirror.com'
```

2.其他科学上网方法，如clash等，然后设置好http/https代理。

```sh
export http_proxy=http://xx.xx.xx.xx:xxxx
export https_proxy=https://xx.xx.xx.xx:xxxx
```

**Comment by chenyang126** [comment]
谢谢，已用手工下载的方式解决！
