### ISSUE TITLE
qwen支持

### ISSUE THREAD

**Issue by Vincent131499** [BestAnHongjun/LMDeploy-Jetson#6]
Great work!!!
请问qwen1.5-1.8B/qwen1.5-0.5B可以支持吗？

**Comment by cavedweller509** [comment]
仅针对InternLM系列模型做过适配支持，第三方模型可自行尝试。理论上显存充足的情况下可以运行LMDeploy官方支持的全部模型。

**Comment by Vincent131499** [comment]
好的，感谢回复，后面验证下
感谢提供的平台！

**Comment by chuangzhidan** [comment]
成功了吗
